export type IFont =
  | 'regular'
  | 'italic'
  | 'light'
  | 'black'
  | 'bold'
  | 'medium'
  | 'thin'
  | 'blackItalic'
  | 'boldItalic'
  | 'lightItalic'
  | 'mediumItalic'
  | 'thinItalic';

export type IFontSize =
  | 'tiny'
  | 'xsmall'
  | 'small'
  | 'default'
  | 'big'
  | 'large'
  | 'xlarge'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'h7'
  | 'h8'
  | 'tabBar'
  | 'body'
  | 'title'
  | 'XXG'
  | 'link'
  | 'desk';

export type IVariants = IOutbackVariants;

export type IOutbackVariants =
  | 'outback:h1'
  | 'outback:h2'
  | 'outback:h3'
  | 'outback:h4'
  | 'outback:h5'
  | 'outback:h6'
  | 'outback:h7'
  | 'outback:h8'
  | 'outback:tabBar'
  | 'outback:body'
  | 'outback:title'
  | 'outback:XXG'
  | 'outback:por'
  | 'outback:link'
  | 'outback:desk';
